### PR TITLE
Added llmstudio functionality

### PR DESCRIPTION
**Pull request by jimmc414**
This PR adds LLMStudio functionality using maestro_ollama.py as a template

### CODE REVIEW

**Comment by Doriandarko** [comment]
I just finished a script that does this as well. I want to test it a little more deeply before pushing the update

**Comment by jimmc414** [comment]
This change has been tested and works the same way as maestro_ollama.py but with LLMStudio instead.

**Comment by jimmc414** [comment]
> I just finished a script that does this as well. I want to test it a little more deeply before pushing the update

Completely understand.  Really appreciate your work.

**Comment by jimmc414** [comment]
👎

**Pull request closed without merging**
